import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-4">
          <Navbar />
          <div className="flex gap-6">
          <Sidebar/>
          <div className="mt-8">{children}</div></div>

        </div>
      </body>
    </html>
  );
}
